version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: monitoring-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: monitor
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  demo-app:
    image: nginx:1.27-alpine
    container_name: monitoring-demo-app
    restart: unless-stopped
    command: ["/bin/sh", "-c", "echo 'ok' > /usr/share/nginx/html/health && nginx -g 'daemon off;'"]
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    image: alpine:3.20
    container_name: monitoring-worker
    restart: unless-stopped
    command: ["sh", "-c", "while true; do sleep 300; done"]

volumes:
  db_data:
